global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.Globalization;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.ComponentModel.DataAnnotations;
global using Vehicle.Data.Entities;
global using Microsoft.EntityFrameworkCore;
global using System.Windows.Forms;
global using Vehicle.Data;
global using Vehicle.Data.Entities;
global using Vehicle.Ui.Extensions;
global using Vehicle.Ui.ViewModels;
global using static Vehicle.Ui.Extensions.ObjectExtensions;
